/*
 * StepperMotor_config.h
 *
 *  Created on: Oct 16, 2021
 *      Author: sa7er
 */

#ifndef HAL_STEPPERMOTOR_CONFIG_H_
#define HAL_STEPPERMOTOR_CONFIG_H_

#define STEPPER_MOTOR_u8BLUE_PORT		DIO_u8GROUP_B
#define STEPPER_MOTOR_u8BLUE_PIN		DIO_u8PIN4

#define STEPPER_MOTOR_u8PINK_PORT		DIO_u8GROUP_B
#define STEPPER_MOTOR_u8PINK_PIN		DIO_u8PIN5

#define STEPPER_MOTOR_u8YELLOW_PORT		DIO_u8GROUP_B
#define STEPPER_MOTOR_u8YELLOW_PIN		DIO_u8PIN6

#define STEPPER_MOTOR_u8ORANGE_PORT		DIO_u8GROUP_B
#define STEPPER_MOTOR_u8ORANGE_PIN		DIO_u8PIN7


#endif /* HAL_STEPPERMOTOR_CONFIG_H_ */
