/*
 * DIO_config.h
 *
 *  Created on: Sep 28, 2021
 *      Author: sa7er
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*               output is DIO_u8OUTPUT and input is DIO_u8INPUT              */

#define DIO_u8PORTA_PIN0_DIR			DIO_u8OUTPUT
#define DIO_u8PORTA_PIN1_DIR			DIO_u8OUTPUT
#define DIO_u8PORTA_PIN2_DIR			DIO_u8OUTPUT
#define DIO_u8PORTA_PIN3_DIR			DIO_u8OUTPUT
#define DIO_u8PORTA_PIN4_DIR			DIO_u8INPUT
#define DIO_u8PORTA_PIN5_DIR			DIO_u8INPUT
#define DIO_u8PORTA_PIN6_DIR			DIO_u8INPUT
#define DIO_u8PORTA_PIN7_DIR			DIO_u8INPUT

#define DIO_u8PORTB_PIN0_DIR			DIO_u8OUTPUT
#define DIO_u8PORTB_PIN1_DIR			DIO_u8OUTPUT
#define DIO_u8PORTB_PIN2_DIR			DIO_u8OUTPUT
#define DIO_u8PORTB_PIN3_DIR			DIO_u8OUTPUT
#define DIO_u8PORTB_PIN4_DIR			DIO_u8INPUT
#define DIO_u8PORTB_PIN5_DIR			DIO_u8INPUT
#define DIO_u8PORTB_PIN6_DIR			DIO_u8INPUT
#define DIO_u8PORTB_PIN7_DIR			DIO_u8INPUT

#define DIO_u8PORTC_PIN0_DIR			DIO_u8OUTPUT
#define DIO_u8PORTC_PIN1_DIR			DIO_u8OUTPUT
#define DIO_u8PORTC_PIN2_DIR			DIO_u8OUTPUT
#define DIO_u8PORTC_PIN3_DIR			DIO_u8OUTPUT
#define DIO_u8PORTC_PIN4_DIR			DIO_u8INPUT
#define DIO_u8PORTC_PIN5_DIR			DIO_u8INPUT
#define DIO_u8PORTC_PIN6_DIR			DIO_u8INPUT
#define DIO_u8PORTC_PIN7_DIR			DIO_u8INPUT

#define DIO_u8PORTD_PIN0_DIR			DIO_u8OUTPUT
#define DIO_u8PORTD_PIN1_DIR			DIO_u8OUTPUT
#define DIO_u8PORTD_PIN2_DIR			DIO_u8OUTPUT
#define DIO_u8PORTD_PIN3_DIR			DIO_u8OUTPUT
#define DIO_u8PORTD_PIN4_DIR			DIO_u8INPUT
#define DIO_u8PORTD_PIN5_DIR			DIO_u8INPUT
#define DIO_u8PORTD_PIN6_DIR			DIO_u8INPUT
#define DIO_u8PORTD_PIN7_DIR			DIO_u8INPUT


/*               output value is DIO_u8HIGH or DIO_u8LOW and input value is DIO_u8PULL_UP or  DIO_u8FLOAT  */

#define DIO_u8PORTA_PIN0_VALUE			DIO_u8HIGH
#define DIO_u8PORTA_PIN1_VALUE			DIO_u8LOW
#define DIO_u8PORTA_PIN2_VALUE			DIO_u8HIGH
#define DIO_u8PORTA_PIN3_VALUE			DIO_u8LOW
#define DIO_u8PORTA_PIN4_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTA_PIN5_VALUE			DIO_u8FLOAT
#define DIO_u8PORTA_PIN6_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTA_PIN7_VALUE			DIO_u8FLOAT

#define DIO_u8PORTB_PIN0_VALUE			DIO_u8HIGH
#define DIO_u8PORTB_PIN1_VALUE			DIO_u8LOW
#define DIO_u8PORTB_PIN2_VALUE			DIO_u8HIGH
#define DIO_u8PORTB_PIN3_VALUE			DIO_u8LOW
#define DIO_u8PORTB_PIN4_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTB_PIN5_VALUE			DIO_u8FLOAT
#define DIO_u8PORTB_PIN6_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTB_PIN7_VALUE			DIO_u8FLOAT

#define DIO_u8PORTC_PIN0_VALUE			DIO_u8HIGH
#define DIO_u8PORTC_PIN1_VALUE			DIO_u8LOW
#define DIO_u8PORTC_PIN2_VALUE			DIO_u8HIGH
#define DIO_u8PORTC_PIN3_VALUE			DIO_u8LOW
#define DIO_u8PORTC_PIN4_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTC_PIN5_VALUE			DIO_u8FLOAT
#define DIO_u8PORTC_PIN6_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTC_PIN7_VALUE			DIO_u8FLOAT

#define DIO_u8PORTD_PIN0_VALUE			DIO_u8HIGH
#define DIO_u8PORTD_PIN1_VALUE			DIO_u8LOW
#define DIO_u8PORTD_PIN2_VALUE			DIO_u8HIGH
#define DIO_u8PORTD_PIN3_VALUE			DIO_u8LOW
#define DIO_u8PORTD_PIN4_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTD_PIN5_VALUE			DIO_u8FLOAT
#define DIO_u8PORTD_PIN6_VALUE			DIO_u8PULL_UP
#define DIO_u8PORTD_PIN7_VALUE			DIO_u8FLOAT


#endif /* DIO_CONFIG_H_ */
